#!/bin/bash

echo "📦 GitHub Push Helper"
echo "===================="
echo ""
echo "Your code is committed locally with message:"
echo "Add Telegram automation system for 500 subscriber growth"
echo ""
echo "To push to GitHub, you need to:"
echo ""
echo "1. First, create the repository on GitHub:"
echo "   Go to: https://github.com/new"
echo "   Name: ai-finance-agency"
echo "   Make it Private or Public"
echo "   DON'T initialize with README"
echo ""
echo "2. Then run this command:"
echo "   git push -u origin main"
echo ""
echo "If prompted for authentication:"
echo "   Username: srijanarya"
echo "   Password: Your GitHub Personal Access Token"
echo ""
echo "To create a Personal Access Token:"
echo "   1. Go to https://github.com/settings/tokens"
echo "   2. Click 'Generate new token'"
echo "   3. Select 'repo' scope"
echo "   4. Copy the token and use it as password"
echo ""
echo "Alternative: Use GitHub CLI"
echo "   brew install gh"
echo "   gh auth login"
echo "   gh repo create ai-finance-agency --private --source=."
echo ""
echo "Your commit includes:"
echo "   - 179 files changed"
echo "   - 24,091 lines added"
echo "   - Complete Telegram automation system"
echo ""
echo "Press Enter to try pushing now, or Ctrl+C to exit..."
read

echo "Attempting to push..."
git push -u origin main