# AI Finance Agency - Scaling Configuration
# Add new AI models and data sources here

ai_models:
  # Current Models
  claude:
    provider: anthropic
    model: claude-3-opus-20240229
    use_cases:
      - market_analysis
      - compliance_checks
      - risk_assessment
    
  openai:
    provider: openai
    model: gpt-4
    use_cases:
      - content_generation
      - educational_material
      - creative_writing
  
  # Add New Models Here
  gemini:
    provider: google
    model: gemini-pro
    api_key: ${GOOGLE_AI_KEY}
    use_cases:
      - multimodal_analysis
      - chart_interpretation
    
  llama:
    provider: meta
    model: llama-2-70b
    endpoint: http://localhost:8080  # Local deployment
    use_cases:
      - code_generation
      - technical_documentation
    
  mistral:
    provider: mistral
    model: mistral-medium
    api_key: ${MISTRAL_API_KEY}
    use_cases:
      - european_markets
      - multilingual_content

market_data_sources:
  # Current Sources
  alpha_vantage:
    endpoint: https://www.alphavantage.co/query
    api_key: ${ALPHA_VANTAGE_API_KEY}
    data_types:
      - stocks
      - forex
      - crypto
    
  finnhub:
    endpoint: https://finnhub.io/api/v1
    api_key: ${FINNHUB_API_KEY}
    data_types:
      - real_time_quotes
      - company_news
      - earnings
    
  polygon:
    endpoint: https://api.polygon.io
    api_key: ${POLYGON_API_KEY}
    data_types:
      - options
      - aggregates
      - snapshots
  
  # Add New Data Sources
  yahoo_finance:
    endpoint: https://query1.finance.yahoo.com
    data_types:
      - historical_data
      - dividends
      - splits
    
  coinmarketcap:
    endpoint: https://pro-api.coinmarketcap.com
    api_key: ${COINMARKETCAP_API_KEY}
    data_types:
      - crypto_rankings
      - market_cap
      - volume
    
  bloomberg:
    endpoint: https://api.bloomberg.com
    api_key: ${BLOOMBERG_API_KEY}
    data_types:
      - institutional_data
      - fixed_income
      - commodities
    
  refinitiv:
    endpoint: https://api.refinitiv.com
    api_key: ${REFINITIV_API_KEY}
    data_types:
      - fundamental_data
      - esg_scores
      - supply_chain

social_platforms:
  # Current Platforms
  twitter:
    enabled: true
    api_version: v2
    
  linkedin:
    enabled: true
    oauth: true
    
  # Add New Platforms
  discord:
    enabled: true
    webhook_url: ${DISCORD_WEBHOOK}
    channels:
      - general
      - trading-signals
      - market-analysis
    
  reddit:
    enabled: true
    subreddits:
      - r/algotrading
      - r/stocks
      - r/cryptocurrency
    
  youtube:
    enabled: true
    api_key: ${YOUTUBE_API_KEY}
    content_types:
      - market_recap_videos
      - educational_shorts

scaling_options:
  # Horizontal Scaling
  microservices:
    replicas:
      api_gateway: 3
      trading_service: 5
      signals_service: 3
      market_data: 4
    
  # Load Balancing
  load_balancer:
    type: nginx
    algorithm: round_robin
    health_check_interval: 30s
    
  # Caching
  redis:
    max_memory: 2gb
    eviction_policy: lru
    persistence: true
    
  # Message Queue
  rabbitmq:
    prefetch_count: 10
    max_connections: 1000
    queue_durability: true
    
  # Database
  postgresql:
    max_connections: 200
    connection_pool: 50
    read_replicas: 2
    
performance_targets:
  api_response_time: 50ms
  throughput: 10000_requests_per_second
  availability: 99.99%
  data_latency: 10ms
  ai_inference_time: 500ms