apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: treum-staging
  labels:
    app: api-gateway
    service: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api-gateway

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-service-account
  namespace: treum-staging
  labels:
    app: api-gateway

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-role
  namespace: treum-staging
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-rolebinding
  namespace: treum-staging
subjects:
  - kind: ServiceAccount
    name: api-gateway-service-account
    namespace: treum-staging
roleRef:
  kind: Role
  name: api-gateway-role
  apiGroup: rbac.authorization.k8s.io