# AI Finance Agency - Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ai-finance-agency'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # AI Finance Agency Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'trading'
    static_configs:
      - targets: ['trading:3004']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:3001']
    metrics_path: /metrics
    scrape_interval: 5s