"""Add email verification token to users table

Revision ID: 112b37a02444
Revises: 001_initial_auth
Create Date: 2025-09-10 03:38:33.307079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112b37a02444'
down_revision = '001_initial_auth'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###