# TalkingPhoto MVP - Streamlit Cloud Production Configuration
# Optimized for cloud deployment and performance

[theme]
# Professional brand colors
primaryColor = "#d96833"  # Orange accent
backgroundColor = "#1b170f"  # Dark background
secondaryBackgroundColor = "#2c2416"  # Secondary dark
textColor = "#ece7e2"  # Light text
font = "Inter, sans-serif"  # Modern font

[server]
# Production server settings
maxUploadSize = 25  # Reduced for cloud deployment
maxMessageSize = 25  # Optimized for cloud
enableCORS = true
enableXsrfProtection = true
port = 8501
headless = true  # Required for cloud deployment
runOnSave = false  # Disabled for production
enableStaticServing = true

# Performance optimizations
maxCachedMessageSize = 100
allowRunOnSave = false

[browser]
# Browser configuration
gatherUsageStats = false  # Privacy compliant
showErrorDetails = false  # Hide sensitive errors in production
serverAddress = "0.0.0.0"  # Listen on all interfaces

[logger]
# Production logging
level = "INFO"
enableLogging = true

[runner]
# Execution settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true

[client]
# Client-side optimizations
caching = true
showErrorDetails = false
toolbarMode = "minimal"

[ui]
# UI optimizations
hideTopBar = false
hideSidebarNav = false
wideMode = false  # Consistent layout
sidebarState = "collapsed"  # Start collapsed

[global]
# Global settings
developmentMode = false
suppressConnectionWarning = true
showWarningOnDirectExecution = false

# Cache settings
[cache]
maxEntries = 1000
ttlSeconds = 3600  # 1 hour cache
persist = true

# Upload settings
[fileWatcher]
watcherType = "none"  # Disable file watching in production

# Security settings
[security]
enableWebsocketCompression = true
allowWebsocketOrigin = "*"

# Memory management
[memory]
maxCacheSize = "1GB"
garbageCollectorThreshold = 0.8

# Performance monitoring
[metrics]
enableMetrics = true
metricsAddr = "127.0.0.1:8502"