# TalkingPhoto MVP Production Secrets
# This file should be configured in Streamlit Cloud's secrets management

# AI Video Generation Services (Priority Order)
[heygen]
api_key = "YOUR_HEYGEN_API_KEY"
api_endpoint = "https://api.heygen.com/v1"

[d_id]
api_key = "YOUR_D_ID_API_KEY"
api_endpoint = "https://api.d-id.com"

[synthesia]
api_key = "YOUR_SYNTHESIA_API_KEY"
api_endpoint = "https://api.synthesia.io"

[luma_ai]
api_key = "YOUR_LUMA_AI_API_KEY"
api_endpoint = "https://api.luma-ai.com"

# Payment Processing (Production Keys)
[stripe]
publishable_key = "pk_live_YOUR_STRIPE_PUBLISHABLE_KEY"
secret_key = "sk_live_YOUR_STRIPE_SECRET_KEY"
webhook_secret = "whsec_YOUR_WEBHOOK_SECRET"
price_id_monthly = "price_YOUR_MONTHLY_PRICE_ID"
price_id_yearly = "price_YOUR_YEARLY_PRICE_ID"

# Indian Payment Gateway
[razorpay]
key_id = "rzp_live_YOUR_RAZORPAY_KEY"
key_secret = "YOUR_RAZORPAY_SECRET"

# Cloud Storage (Production)
[cloudinary]
cloud_name = "YOUR_CLOUD_NAME"
api_key = "YOUR_CLOUDINARY_API_KEY"
api_secret = "YOUR_CLOUDINARY_API_SECRET"

[aws]
access_key_id = "YOUR_AWS_ACCESS_KEY"
secret_access_key = "YOUR_AWS_SECRET_KEY"
s3_bucket = "talkingphoto-storage"
region = "us-east-1"

# Analytics & Monitoring
[analytics]
google_analytics_id = "G-XXXXXXXXXX"
mixpanel_token = "YOUR_MIXPANEL_TOKEN"
posthog_api_key = "YOUR_POSTHOG_API_KEY"

[sentry]
dsn = "YOUR_SENTRY_DSN"
environment = "production"

# Database (Optional - for user tracking)
[supabase]
url = "YOUR_SUPABASE_URL"
anon_key = "YOUR_SUPABASE_ANON_KEY"
service_role_key = "YOUR_SUPABASE_SERVICE_KEY"

# Email Service (Optional)
[sendgrid]
api_key = "YOUR_SENDGRID_API_KEY"
from_email = "noreply@talkingphoto.ai"

# Security & Authentication
[jwt]
secret_key = "YOUR_JWT_SECRET_KEY_MIN_32_CHARS"
algorithm = "HS256"
expire_minutes = 30

# Rate Limiting & Security
[security]
max_requests_per_hour = 100
max_video_generations_per_day = 10
max_file_size_mb = 25

# App Configuration
[app]
environment = "production"
debug = false
log_level = "INFO"
max_concurrent_jobs = 5

# Feature Flags
[features]
enable_payments = true
enable_analytics = true
enable_caching = true
enable_social_sharing = true
enable_advanced_options = true
enable_mobile_upload = true

# Veo3 Configuration (Primary Provider)
[veo3]
api_key = "YOUR_VEO3_API_KEY"
api_endpoint = "https://api.veo3.ai/v1"
model = "veo3-pro"
max_duration = 30
quality = "1080p"

# Redis Alternative (Streamlit Cloud Compatible)
[cache]
provider = "streamlit"  # Uses Streamlit's built-in caching
ttl_seconds = 3600

# Webhook Configuration
[webhooks]
stripe_endpoint = "/webhook/stripe"
razorpay_endpoint = "/webhook/razorpay"