# Kubernetes namespace for AI Finance Agency
apiVersion: v1
kind: Namespace
metadata:
  name: ai-finance-agency
  labels:
    name: ai-finance-agency
    environment: production
    app: ai-finance-agency
  annotations:
    description: "AI Finance Agency platform namespace"
    contact: "devops@ai-finance-agency.com"
---
# Resource quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-finance-resource-quota
  namespace: ai-finance-agency
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
# Limit range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-finance-limit-range
  namespace: ai-finance-agency
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container