name: Posting Monitor & Recovery (Fixed)

on:
  schedule:
    # Run every hour to check for missed posts
    - cron: '15 * * * *'  # 15 minutes past every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install minimal required dependencies
        pip install requests python-dotenv openai yfinance pandas numpy
        pip install tweepy feedparser beautifulsoup4 lxml schedule
        echo "✅ Dependencies installed"
    
    - name: Check for missed posts
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        echo "🔍 Checking for missed posts..."
        
        # Check if posting_monitor.py exists
        if [ -f "posting_monitor.py" ]; then
          python posting_monitor.py
        else
          echo "⚠️ posting_monitor.py not found, running cloud_poster.py directly"
          python cloud_poster.py
        fi
        
        echo "✅ Monitoring complete!"
    
    # NO GIT COMMIT - Avoid permission issues
    # NO ARTIFACT UPLOAD - Avoid v3 deprecation issues